FROM node:14.18.1-alpine

WORKDIR /app

# Important for the caching of the layers
COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci

COPY app/. .

EXPOSE 8080

CMD npm start