version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    image: aefimow/devops-for-programmers-project-74
    environment: {}
    command: npm test
    depends_on:
      - "db"

  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  