version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: bash -c 'sleep 3 && npm start'
    volumes:
      - ./app:/app

  caddy:
    image: caddy:2.6.2
    restart: unless-stopped
    environment: {}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "app"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile