version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    image: aefimow/devops-for-programmers-project-74
    environment: {}
    command: npm test