version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    image: aefimow/devops-for-programmers-project-74
    environment: 
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
    command: npm test
    depends_on:
      - "db"

  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password